Course Materials/09-Django-Admin-Portal/my_car_site_v02/cars/urls.py
from django.urls import path 
from . import views

app_name = 'cars'
# domain.com/cars/delete
urlpatterns = [
    path('list/',views.list,name='list'),
    path('add/',views.add,name='add'),
    path('delete/',views.delete,name='delete'),
]

Course Materials/09-Django-Admin-Portal/my_car_site_v02/my_car_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/',include('cars.urls'))
]

Course Materials/09-Django-Admin-Portal/my_car_site_v02/cars/models.py
from django.db import models

# Create your models here.

class Car(models.Model):
    # UNI ID
    brand = models.CharField(max_length=30)
    year = models.IntegerField() 

    def __str__(self):
        return f"Car is {self.brand} {self.year}" 

Course Materials/09-Django-Admin-Portal/my_car_site_v02/cars/views.py
from django.shortcuts import render,redirect 
from django.urls import reverse
from . import models

# Create your views here.
def list(request):

    all_cars = models.Car.objects.all()

    context = {'all_cars':all_cars}

    return render(request,'cars/list.html',context=context)

def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand,year=year)
        
        return redirect(reverse('cars:list'))
    else:    
        return render(request,'cars/add.html')

def delete(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse('cars:list'))
        except:
            print('pk not found') # later on we can use Django messages
            return redirect(reverse('cars:list'))
    else:    
        return render(request,'cars/delete.html')

Course Materials/09-Django-Admin-Portal/my_car_site_v02/cars/templates/cars/add.html
{% extends "base.html" %}

{% block content%}

<div class='container'>
    <h1>ADD.html</h1>
    
    <form action="" method='POST'>

        {% csrf_token %}

        <div class="form-group">
        <label for="brand">BRAND</label>
        <input  id='brand' class="form-control" type="text" name='brand'>
        </div> 
        <div class="form-group">
            <label  for="year">YEAR</label>
            <input class="form-control" type="text" id='year' name='year'>
        </div><br>
        <input type="submit">

    </form>
</div>

{% endblock%}

Course Materials/09-Django-Admin-Portal/my_car_site_v02/cars/templates/cars/delete.html
{% extends "base.html" %}

{% block content%}

<div class='container'>
    <h1>DELETE.HTML</h1>
    
    <form action="" method='POST'>

        {% csrf_token %}

        <div class="form-group">
        <label for="pk">PK NUMBER</label>
        <input  id='pk' class="form-control" type="text" name='pk'>
        </div> 
        
        <input type="submit">

    </form>
</div>
<h1>{{issue}}</h1>
{% endblock%}

Course Materials/09-Django-Admin-Portal/my_car_site_v02/cars/templates/cars/list.html
{% extends "base.html" %}

{% block content%}

<h1>LIST.HTML</h1>
<div class='container'>

    <ul>
        {%for car in all_cars %}
        <li>{{car.brand}} {{car.year}}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

Course Materials/09-Django-Admin-Portal/my_car_site_v02/templates/base.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <title>Document</title>
</head>
<body>

  <!-- NAVBAR -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid"> 
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav"> 
          <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
          <a class="nav-link" href="{% url 'cars:add' %}">ADD</a> 
          <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a> 
        </div>
      </div>
    </div>
  </nav>
{%block content%}
{% endblock %}  
</body>
</html>